### ISSUE TITLE
sqlite3.OperationalError: database is locked

### ISSUE THREAD

**Issue by nidhish1996** [requests-cache/requests-cache#870]
### The problem
sqlite3.OperationalError: database is locked

ERROR 2023-07-05 10:13:30,045 log 125862 140567150999296 Internal Server Error: /login/
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/asgiref/sync.py", line 472, in thread_handler
    raise exc_info[1]
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 43, in inner
    response = await get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "/usr/local/lib/python3.8/site-packages/asgiref/sync.py", line 435, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "/usr/local/lib/python3.8/asyncio/tasks.py", line 455, in wait_for
    return await fut
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/site-packages/asgiref/sync.py", line 476, in thread_handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 414, in initial
    self.perform_authentication(request)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 324, in perform_authentication
    request.user
  File "/usr/local/lib/python3.8/site-packages/rest_framework/request.py", line 227, in user
    self._authenticate()
  File "/usr/local/lib/python3.8/site-packages/rest_framework/request.py", line 380, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
  File "/my_project/authentication.py", line 33, in authenticate
    validator = PyJwtVerifier(id_token, auto_verify=False)
  File "/usr/local/lib/python3.8/site-packages/py_jwt_verifier/__init__.py", line 75, in __init__
    self.jwk = JWK(PyJwtException, cache_enabled, cache_lifetime, cache_store, cache_store_connection)
  File "/usr/local/lib/python3.8/site-packages/py_jwt_verifier/jwk/__init__.py", line 25, in __init__
    requests_cache.install_cache(expire_after=self.cache_lifetime, backend=self.cache_store, connection=cache_store_connection)
  File "/usr/local/lib/python3.8/site-packages/requests_cache/patcher.py", line 42, in install_cache
    backend = init_backend(cache_name, backend, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests_cache/backends/__init__.py", line 91, in init_backend
    return BACKEND_CLASSES[backend](cache_name, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests_cache/backends/sqlite.py", line 57, in __init__
    self.responses: SQLiteDict = SQLiteDict(db_path, table_name='responses', **skwargs)
  File "/usr/local/lib/python3.8/site-packages/requests_cache/backends/sqlite.py", line 194, in __init__
    self.init_db()
  File "/usr/local/lib/python3.8/site-packages/requests_cache/backends/sqlite.py", line 206, in init_db
    con.execute(
sqlite3.OperationalError: database is locked

### Steps to reproduce the behavior
The issue arises randomly

### Environment
- requests-cache version: 1.1.0
- Python version: 3.8
- Platform: Docker version 20.10.22

**Comment by JWCook** [comment]
Based on the traceback, it looks like you're using the patcher (which isn't thread-safe) in a multithreaded application. There are more details on this in the documentation.

**Comment by nidhish1996** [comment]
ERROR 2023-09-12 11:59:56,933 log 9262 140569142195968 Internal Server Error: /test/
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/asgiref/sync.py", line 472, in thread_handler
    raise exc_info[1]
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 43, in inner
    response = await get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "/usr/local/lib/python3.8/site-packages/asgiref/sync.py", line 435, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "/usr/local/lib/python3.8/asyncio/tasks.py", line 455, in wait_for
    return await fut
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/site-packages/asgiref/sync.py", line 476, in thread_handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 414, in initial
    self.perform_authentication(request)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 324, in perform_authentication
    request.user
  File "/usr/local/lib/python3.8/site-packages/rest_framework/request.py", line 227, in user
    self._authenticate()
  File "/usr/local/lib/python3.8/site-packages/rest_framework/request.py", line 380, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
  File "/my_project/authentication.py", line 33, in authenticate
    validator = PyJwtVerifier(id_token, auto_verify=False)
  File "/usr/local/lib/python3.8/site-packages/py_jwt_verifier/__init__.py", line 75, in __init__
    self.jwk = JWK(PyJwtException, cache_enabled, cache_lifetime, cache_store, cache_store_connection)
  File "/usr/local/lib/python3.8/site-packages/py_jwt_verifier/jwk/__init__.py", line 25, in __init__
    requests_cache.install_cache(expire_after=self.cache_lifetime, backend=self.cache_store, connection=cache_store_connection)
  File "/usr/local/lib/python3.8/site-packages/requests_cache/patcher.py", line 42, in install_cache
    backend = init_backend(cache_name, backend, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests_cache/backends/__init__.py", line 91, in init_backend
    return BACKEND_CLASSES[backend](cache_name, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests_cache/backends/sqlite.py", line 62, in __init__
    self.responses: SQLiteDict = SQLiteDict(db_path, table_name='responses', **skwargs)
  File "/usr/local/lib/python3.8/site-packages/requests_cache/backends/sqlite.py", line 208, in __init__
    self.init_db()
  File "/usr/local/lib/python3.8/site-packages/requests_cache/backends/sqlite.py", line 220, in init_db
    con.execute(
sqlite3.OperationalError: database is locked

@JWCook I updated the package version to 1.1.0 and still I am getting this error. could you please mention the additional steps I need to take to avoid this?

**Comment by JWCook** [comment]
I think you can find all the info you need in the docs ([starting here](https://requests-cache.readthedocs.io/en/stable/user_guide/general.html)). The problem is that you're using the patcher (which isn't thread-safe) in a multithreaded application. The solution is to use `CachedSession` instead, which is thread-safe.
