### ISSUE TITLE
Header values in bytes from `OAuth1Session` by `requests-oauthlib` are not accepted

### ISSUE THREAD

**Issue by cenviity** [requests-cache/requests-cache#964]
### The problem

This is a similar issue as #705.

When using `requests_cache` with `OAuth1Session` or `OAuth1` from `requests_oauthlib`, `normalize_headers` fails since it expects the header values to be strings when they are in fact all bytes.

See steps to reproduce error and relevant stack trace below.

### Expected behavior
Headers should be parsed and handled correctly even if they are bytes instead of strings.

### Steps to reproduce the behavior

Example code:

```python
from requests_cache import CacheMixin
from requests_oauthlib import OAuth1Session

url = "SOME_URL"
client_key = "SOME_CLIENT_KEY"
client_secret = "SOME_CLIENT_SECRET"


class CachedOAuth1Session(CacheMixin, OAuth1Session):
    pass


if __name__ == "__main__":
    session = CachedOAuth1Session(
        client_key=client_key,
        client_secret=client_secret,
        signature_type="auth_header",
        expire_after=60,
    )

    response = session.get(url)
``` 

Running the code above results in the following error:

```fish
Traceback (most recent call last):
  File "/home/cenviity/projects/oauth-sandbox/requests_oauthlib_oauth1.py", line 37, in <module>
    response = session.get(url)
               ^^^^^^^^^^^^^^^^
  File "/home/cenviity/.cache/pypoetry/virtualenvs/non-package-mode-Pf7_w-zJ-py3.12/lib/python3.12/site-packages/requests_cache/session.py", line 126, in get
    return self.request('GET', url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cenviity/.cache/pypoetry/virtualenvs/non-package-mode-Pf7_w-zJ-py3.12/lib/python3.12/site-packages/requests_cache/session.py", line 182, in request
    return super().request(method, url, *args, headers=headers, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cenviity/.cache/pypoetry/virtualenvs/non-package-mode-Pf7_w-zJ-py3.12/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cenviity/.cache/pypoetry/virtualenvs/non-package-mode-Pf7_w-zJ-py3.12/lib/python3.12/site-packages/requests_cache/session.py", line 211, in send
    self.cache.create_key(request, **kwargs), request, self.settings
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cenviity/.cache/pypoetry/virtualenvs/non-package-mode-Pf7_w-zJ-py3.12/lib/python3.12/site-packages/requests_cache/backends/base.py", line 126, in create_key
    return key_fn(
           ^^^^^^^
  File "/home/cenviity/.cache/pypoetry/virtualenvs/non-package-mode-Pf7_w-zJ-py3.12/lib/python3.12/site-packages/requests_cache/cache_keys.py", line 70, in create_key
    request = normalize_request(request, ignored_parameters)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cenviity/.cache/pypoetry/virtualenvs/non-package-mode-Pf7_w-zJ-py3.12/lib/python3.12/site-packages/requests_cache/cache_keys.py", line 127, in normalize_request
    norm_request.headers = normalize_headers(norm_request.headers, ignored_parameters)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cenviity/.cache/pypoetry/virtualenvs/non-package-mode-Pf7_w-zJ-py3.12/lib/python3.12/site-packages/requests_cache/cache_keys.py", line 139, in normalize_headers
    if ',' in v:
       ^^^^^^^^
TypeError: a bytes-like object is required, not 'str'
```

### Workarounds

This can be fixed by casting header values back to strings first. See added lines with comment below:

```python
# requests_cache/cache_keys.py

def normalize_headers(
    headers: MutableMapping[str, str], ignored_parameters: ParamList = None
) -> CaseInsensitiveDict:
    """Sort and filter request headers, and normalize minor variations in multi-value headers"""
    if ignored_parameters:
        headers = filter_sort_dict(headers, ignored_parameters)
    for k, v in headers.items():
        v = decode(v)  # Cast bytes back to string first
        if ',' in v:
            values = [v.strip() for v in v.lower().split(',') if v.strip()]
            headers[k] = ', '.join(sorted(values))
        else:
            headers[k] = v  # Also update single header values once decoded
    return CaseInsensitiveDict(headers)
```

### Environment
- requests-cache version: 1.2.0
- Python version: 3.12.1
- Platform: macOS Sonoma 14.3

---

**Update 2024-02-26:** Added stack trace. Updated workaround to also update decoded single header values.

**Comment by cenviity** [comment]
Having looked into this a bit more, I think decoding the header values in `normalize_request` (which then calls `normalize_headers`) is a simpler fix. This way we don't have to mess around with the types of `normalize_headers` and other functions that deal with header values assuming they are only ever strings.
