### ISSUE TITLE
`stale_if_error=True` does not handle errors during conditional requests

### ISSUE THREAD

**Issue by federicocagnola** [requests-cache/requests-cache#995]
### The problem
The `stale_if_error=True` option in `CachedSession` does not seem to work as expected. When a cached response is available and the server becomes unreachable, the library raises a `ConnectionError` instead of returning the cached (stale) response. Tested same behavior on HTTP error codes.

### Expected behavior
When `stale_if_error=True` is set and a cached response is available, the library should return the cached response if the server becomes unreachable, even if the response has expired.
From the docs:
```
In some cases, you might cache a response, have it expire, but then encounter an error when retrieving a new response. If you would like to use expired response data in these cases, use the `stale_if_error` option.
[...]
In addition to HTTP error codes, stale_if_error also applies to python exceptions (typically a RequestException). See requests documentation on Errors and Exceptions for more details on request errors in general.
```

### Steps to reproduce the behavior
```python
import logging
import time

logging.basicConfig(level='DEBUG')

from requests.auth import HTTPBasicAuth
from requests_cache import CachedSession, EXPIRE_IMMEDIATELY, RedisCache

http_basic_auth = HTTPBasicAuth(username='myuser', password='mypwd')
backend = RedisCache(
    host='localhost', port=6379, namespace="cache_test",
    ttl=False  # disable redis auto expiry to manage expiration and cache manually
)
session = CachedSession(
    cache_name='cache_test', backend=backend,
    stale_if_error=True,  # use a cached response on error
    expire_after=EXPIRE_IMMEDIATELY,  # consider response expired, but potentially usable
)

def request(url):
    response = session.get(
        url=url, params=None, auth=http_basic_auth,
    )
    print(
        f"GET {url} | cached: {response.from_cache} | status: {response.status_code} | "
        f"created: {response.created_at} | expires: {response.expires}"
    )
    return response

if __name__ == '__main__':
    req_1 = "https://127.0.0.1/req_one"
    req_2 = "https://127.0.0.1/req_two"
    try:
        while True:
            print("*" * 30)
            request(req_1)
            request(req_2)
            print("Sleeping 2 seconds...")
            time.sleep(2)
    except KeyboardInterrupt:
        print("Stopping...")
```

- Start a local web server providing the endpoints.
- Run the script to cache the responses.
- Stop the local web server.
- Observe that the script raises a ConnectionError instead of using the cached response.

Log of the first cached request:
```python
DEBUG:requests_cache.policy.actions:Cache directives from request headers: CacheDirectives()
DEBUG:requests_cache.policy.actions:Pre-read cache checks: Passed
DEBUG:requests_cache.policy.actions:Post-read cache actions: CacheActions(expire_after=0, send_request=True)
GET https://127.0.0.1/req_one | cached: True | status: 200 | created: 2024-07-05 07:43:38.112625+00:00 | expires: 2024-07-05 07:43:44.657025+00:00
DEBUG:urllib3.connectionpool:https://127.0.0.1/ "GET /req_one HTTP/1.1" 304 0
DEBUG:requests_cache.policy.actions:Pre-write cache checks: disabled status
DEBUG:requests_cache.policy.actions:Response for URL https://127.0.0.1/req_one has not been modified
DEBUG:requests_cache.policy.actions:Cache directives from request headers: CacheDirectives()
DEBUG:requests_cache.policy.actions:Pre-read cache checks: Passed
DEBUG:requests_cache.policy.actions:Post-read cache actions: CacheActions(expire_after=0, send_request=True)
DEBUG:urllib3.connectionpool:https://127.0.0.1/ "GET /req_two HTTP/1.1" 304 0
DEBUG:requests_cache.policy.actions:Pre-write cache checks: disabled status
DEBUG:requests_cache.policy.actions:Response for URL https://127.0.0.1/req_one has not been modified
GET https://127.0.0.1/req_one | cached: True | status: 200 | created: 2024-07-05 07:43:38.233563+00:00 | expires: 2024-07-05 07:43:44.741050+00:00
Sleeping 2 seconds...
```
Stopped webserver:
```python
DEBUG:requests_cache.policy.actions:Cache directives from request headers: CacheDirectives()
DEBUG:requests_cache.policy.actions:Pre-read cache checks: Passed
DEBUG:requests_cache.policy.actions:Post-read cache actions: CacheActions(expire_after=0, send_request=True)
DEBUG:urllib3.connectionpool:Resetting dropped connection: localhost
Traceback (most recent call last):
  File "/home/federico/.local/lib/python3.8/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/home/federico/.local/lib/python3.8/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/home/federico/.local/lib/python3.8/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/federico/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
  File "/home/federico/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 404, in _make_request
    self._validate_conn(conn)
  File "/home/federico/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1058, in _validate_conn
    conn.connect()
  File "/home/federico/.local/lib/python3.8/site-packages/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
  File "/home/federico/.local/lib/python3.8/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f8a112c2e50>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/federico/.local/lib/python3.8/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/home/federico/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 799, in urlopen
    retries = retries.increment(
  File "/home/federico/.local/lib/python3.8/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='localhost', port=8445): Max retries exceeded with url: /req_one (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8a112c2e50>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/federico/tmp/cachedclient.py", line 43, in <module>
    request(req_1)
  File "/home/federico/tmp/cachedclient.py", line 27, in request
    response = session.get(
  File "/home/federico/.local/lib/python3.8/site-packages/requests_cache/session.py", line 127, in get
    return self.request('GET', url, params=params, kwargs)
  File "/home/federico/.local/lib/python3.8/site-packages/requests_cache/session.py", line 183, in request
    return super().request(method, url, *args, headers=headers, kwargs)  # type: ignore
  File "/home/federico/.local/lib/python3.8/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, send_kwargs)
  File "/home/federico/.local/lib/python3.8/site-packages/requests_cache/session.py", line 230, in send
    response = self._send_and_cache(request, actions, cached_response, kwargs)
  File "/home/federico/.local/lib/python3.8/site-packages/requests_cache/session.py", line 254, in _send_and_cache
    response = super().send(request, kwargs)
  File "/home/federico/.local/lib/python3.8/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, kwargs)
  File "/home/federico/.local/lib/python3.8/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='localhost', port=8445): Max retries exceeded with url: /req_one (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8a112c2e50>: Failed to establish a new connection: [Errno 111] Connection refused'))
```
### Workarounds
No known workarounds at this time.

### Environment
- requests-cache version: requests-cache==1.2.1
- Python version: Python 3.8.10
- Platform: Ubuntu 20.04.6 LTS x86_64

**Comment by JWCook** [comment]
Thank you for the thorough bug report! It appears that the specific case that's broken is handling `stale_if_error` with conditional requests, which I neglected to cover in unit tests.

I can reproduce this using using `python3 -m http.server` and making requests against local files. `http.server` will automatically add `Last-Modified` headers to the response based on the file's modification time, which will trigger a revalidation request when the cached response expires. Currently, any errors during revalidation aren't being handled as they would be for a normal (non-conditional) request.

I will get that fixed soon.

**Comment by JWCook** [comment]
For reference, here's a minimal reproducible example using httpbin:
```py
import requests
from requests_cache import EXPIRE_IMMEDIATELY, CachedSession
from unittest.mock import patch

session = CachedSession(
    cache_name='cache_test',
    stale_if_error=True,
    expire_after=EXPIRE_IMMEDIATELY,
)

# Send conditional request
url = "https://httpbin.org/etag/etag-1"
print(session.get(url))

# Send request again, but simulate a network error
with patch.object(
    requests.adapters.HTTPAdapter,
    'get_connection_with_tls_context',
    side_effect=ValueError('No network connection!'),
):
    print(session.get(url))
```

**Comment by JWCook** [comment]
Fixes are in main.

**Comment by federicocagnola** [comment]
That was very quick, thank you very much!
